language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: required

cache: pip

before_install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools

install:
  - cd Python; python setup.py install
  - cd ..

script:
  - cd Python; pip install -U .[test]
  - python setup.py test
  - pip install -U .[doc]
  - cd doc; make html
  - cd ..

deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master